@EventCountdownBackend_HostAddress = http://localhost:5022

GET {{EventCountdownBackend_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{EventCountdownBackend_HostAddress}}/api/events/
Accept: application/json

###

DELETE {{EventCountdownBackend_HostAddress}}/api/events/1
Accept: application/json